services:
  api:
    extends:
      file: ./packages/api/docker-compose.yml
      service: api

  mongo:
    extends:
      file: ./packages/api/docker-compose.yml
      service: mongo
    deploy:
      resources:
      limits:
        memory: 512m

  bot:
    extends:
      file: ./packages/bot/docker-compose.yml
      service: bot

volumes:
  mongo-data:
